service: ds-automate

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 512
  cfLogs: true
  profile: trend
functions:
  isolate:
    handler: handler.isolate
  dscloudwatchlog:
    handler: dscloudwatch.log
  configrulelog:
    handler: configrule.log
  cloudwatcheventsdisable:
    handler: cloudwatchevents.disable